# Generated by Django 4.2.16 on 2025-06-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(default='https://ui.shadcn.com/avatars/03.png', max_length=200),
        ),
    ]
